### ISSUE TITLE
dumdum doesn't work with PUT requests

### ISSUE THREAD

**Issue by vivus-ignis** [jar-o/dumdum#1]
Trying to run dumdum with the following command:

`DUMDEBUG=1 dumdum --port 8989 --file response --verbose`
with this content of the file response

```
> PUT
> /foo
< status 200
< header Content-Type: application/json
< body { "Status": "Ok" }
< echo
.
```
i'm getting 400 Bad request if try to reach the endpoint with a command like:

`curl -vX PUT localhost:8080/foo`
After adding a bunch of print's to process_verbs function I can see quite interesting results. 

> DEBUG ---------------->
> "Tokens verbs = ['>', u'P', u'UT']"
> ---------------------->
> DEBUG ---------------->
> "Current verbs = [u'P', u'UT']"
> ---------------------->
> DEBUG ---------------->
> 'parsed string = [[[\'>\', u\'P\', u\'UT\'], [\'>\', u\'/foo\'], [\'<\', \'status\', u\'200\'], [\'<\', \'header\', u\'Content-Type: application/json\'], [\'<\', \'body\', u\'{ "Status": "Ok" }\'], [\'<\', \'echo\']]]'
> ---------------------->
> DEBUG ---------------->
> "Tokens verbs = ['>', u'P', u'UT']"
> ---------------------->
> DEBUG ---------------->
> "Current verbs = [u'P', u'UT']"
> ---------------------->

Below are the changed version of the function with debugging added

```
    def process_verbs(self, tokens): # The VERB line ALWAYS starts a request stanza
        self.reqobj = {}
        # Defaults
        self.respobj = {
            'status': status_map(200),
            'body':'',
        }
        dbg("Tokens verbs = %s" % tokens)
        self.current_verbs = tokens[1:]
        dbg("Current verbs = %s" % self.current_verbs)
        for verb in self.current_verbs:
            if verb not in self.S: self.S[verb] = {}

```
(i've added two dbg commands here).
Tried on two different machines (Amazon Linux, Arch Linux).

Python 2.7.14
dumdum (0.1.5)
pyparsing (2.2.0)

**Comment by jar-o** [comment]
thanks, turns out I should have use `Keyword` instead of `Word` for the HTTP verbs. They were fine until we had a collision, i.e. both `PUT` and `POST` start with `P`.

**Comment by jar-o** [comment]
fixed in https://github.com/jar-o/dumdum/commit/36eccb9d04f7bd42012cf784b6481e98a0b7741c thanks for bringing it up, and sorry for the delay.
